# This is a basic workflow to help you get started with Actions

name: 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Test Coverage for files changed in this PR: [http://go/sparkly-pr-coverage/${{ github.event.number }}](https://coverage-browser-dot-etsy-bizdata-gcp-prod.uc.r.appspot.com/sparkly/diff/${{ github.event.number }} "Test Coverage Delta for PR ${{ github.event.number }}").
            Note: Coverage link above will not work until Cloudbuild test runner in this PR is finished.

