name: "Comment Code Coverage of PR"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    # Ignoring Paths that would not have code coverage changes associated with them. 
    paths-ignore:
      - 'sparkly-docs/**'
      - 'build/**'
      - 'project/**'
      - 'scripts/**'
jobs:
  # This job writes out comments to a PR
  pr_commenter:
    name: "Code Coverage Pr Comment"
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          # Code coverage diff webpage uses the PR number in the link, so the pr number variable is used to build the link. 
          message: |
            Test Coverage for files changed in this PR: [http://go/sparkly-pr-coverage/${{ github.event.number }}](https://coverage-browser-dot-etsy-bizdata-gcp-prod.uc.r.appspot.com/sparkly/diff/${{ github.event.number }} "Test Coverage Delta for PR ${{ github.event.number }}").
            Note: Coverage link above will not work until Cloudbuild test runner in this PR is finished.
